version: '3'
services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todoListDev

    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

volumes:
  postgres_data:
